### ISSUE TITLE
Strange Error

### ISSUE THREAD

**Issue by applesnake** [ioquatix/ffi-clang#42]
require 'ffi'
require 'ffi/clang'
class TestStruct < FFI::Struct
  layout :a,:int,
         :b,:int,
         :c,:pointer
end

 ERROR Message:
Traceback (most recent call last):
	6: from t-ffistruct.rb:3:in `<main>'
	5: from t-ffistruct.rb:4:in `<class:TestStruct>'
	4: from /usr/local/lib/ruby/gems/2.6.0/gems/ffi-1.11.1/lib/ffi/struct.rb:218:in `layout'
	3: from /usr/local/lib/ruby/gems/2.6.0/gems/ffi-1.11.1/lib/ffi/struct.rb:306:in `array_layout'
	2: from /usr/local/lib/ruby/gems/2.6.0/gems/ffi-1.11.1/lib/ffi/struct.rb:266:in `find_field_type'
	1: from /usr/local/lib/ruby/gems/2.6.0/gems/ffi-1.11.1/lib/ffi/struct.rb:272:in `find_type'
/usr/local/lib/ruby/2.6.0/mkmf.rb:1255:in `find_type': wrong number of arguments (given 1, expected 2+) (ArgumentError)

Remove: require 'ffi/clang', no error anymore.

**Comment by ioquatix** [comment]
Maybe the way you are using `layout` is wrong?

**Comment by take-cheeze** [comment]
Very strange issue.
Had some investigation and found the cause: mkmf
mkmf gem includes a module called [MakeMakefile](https://ruby-doc.org/stdlib-2.6.3/libdoc/mkmf/rdoc/MakeMakefile.html) in Object class and is seems to polluting the global class.
And workaround you can take is to:

```ruby
module MakeMakefile
  undef find_type
end
```

Though I feel using mkmf in non build stage isn't a good idea so https://github.com/ioquatix/ffi-clang/blob/e59f5882c15d1ebdc077d871173a984c4a5fafad/lib/ffi/clang/lib.rb#L22 should be removed.

**Comment by ioquatix** [comment]
That makes sense, can you make a PR?

**Comment by take-cheeze** [comment]
Seems this workaround is fine too:
```ruby
class Object
  undef find_type
end
```

**Comment by ioquatix** [comment]
Maybe we can fix mkmf?
